use_frameworks!

pod 'AFNetworking', '~> 2.5'
pod 'BDBOAuth1Manager'
pod 'Cosmos', '~> 6.0.1'

# def testing_pods
#    pod 'Quick'
#    pod 'Nimble'
# end

# target 'UnitTests' do
#    testing_pods
# end

target 'Where I Work' do
  pod 'GoogleMaps'
  pod 'AzureSDK-iOS'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'Google'
  pod 'Google/SignIn'
#  pod 'AzureStorageAPIClient'
#  pod 'WindowsAzureMobileServices'       
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '3.0'
		end
	end
end

