use_frameworks!

pod 'AFNetworking', '~> 2.5'
pod 'BDBOAuth1Manager'

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'WhereIWork.UnitTests' do
    testing_pods
end

target 'WhereIWork.UITests' do
    testing_pods
end