use_frameworks!

pod 'AFNetworking', '~> 2.5'
pod 'BDBOAuth1Manager'
pod 'Cosmos', '~> 1.2'

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'UnitTests' do
    testing_pods
end

target 'Where I Work' do
  pod 'GoogleMaps'
  pod 'AzureSDK-iOS'
#  pod 'AzureStorageAPIClient'
#  pod 'WindowsAzureMobileServices'       
end
